server:
  port: 8082  # 每个服务单独端口
feign:
  okhttp:   # okhttp连接池
    enable: true  # 开启连接池支持
hm:
  db:
    database: hm-cart
  swagger:
    title: "xiaoR商城购物车服务接口文档"
    package: com.hm.cart.controller
